exclude: |
  (?x)(
    .chglog|
    ^CHANGELOG.md
  )
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.43.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: check-symlinks
      - id: detect-aws-credentials
      - id: detect-private-key
  - repo: https://github.com/thlorenz/doctoc
    rev: v1.4.0
    hooks:
      - id: doctoc
        args: [--notitle, --maxlevel=3]
