style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/basefarm/terraform-aws-ecs-container-definition
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - doc
        - add
  commit_groups:
    title_maps:
      feat: Features
      add: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      doc: Documentation
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
